language: node_js
cache: yarn
node_js:
- '11'
script:
- npm i bs-platform --no-save
- npm run build
- npm test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
    repo: ryb73/bs-jsonwebtoken
  api_key:
    secure: o73amcQ5TDbPiiIzUgyELxHaQGzD6Hd/c2P6+Km1R9STZmGBqR+sbaLSrdjzoqRBx85WLPv1MzKtIOmxIfyFgtSeESiQYxLNbOp5sXxxS4OKK24qt9yRFbPMPeNG0yyDlj4m3o9E2XPzcC3AS1yVLUFvnbIk7eJw5VbPsg5rKt/uEGApV/UpuJr/pE4FMEipcUjTkKnNVPL1smF4g7aArWVqhgQqZBD01H0rlp54LkT4RTvr9uvwaz6a4hNhbI4uvlHdD/+eSCGr9GKCHLazRdILI+16z9z7N8EQwfMTSvnkvfr+e8bmAeb85paH6xKAlUXoBdioJJu/hxPdnWOBR0M1DBiNECBbKLfLplrczzFfL+9khjtDgc/vDKAtCMf371uCuTFsfTFhNqn4skiGNMTffqpdnyXb9oa/x4xY8JJr0sWWPxyL+er86ctJ+ZMMyJ7GJSphby+Qq9uErYWaoWj/PDBr/aZWyhd7KHXUwf+lF4JOZPQ4xr3eTuIs3TP+RSEf6yQGf5/QYMSfNnAX8yVCo5mfX3V5cwU+fRSjTY+Y1fshAHZ8l2YVQZTQDqAmrghvUhUc6P+4YhkPGIbR/3zf2e3mlYEtdlWAeVWKvPJTH2DW+o2dkKfBSE7oYuZTQXNvIIuA9dqXKutL8bJsVFToJD7rWXv5rDleQ6lHrUs=
